### ISSUE TITLE
RUSTSEC-2020-0036: failure: failure is officially deprecated/unmaintained

### ISSUE THREAD

**Issue by brightly-salty** [timvisee/ffsend-api#71]
When `cargo-audit` is run on any project with a direct or indirect dependency on ffsend-api, the following is output (for more info, see https://rustsec.org/advisories/RUSTSEC-2020-0036):

```
Crate:         failure
Version:       0.1.8
Warning:       unmaintained
Title:         failure is officially deprecated/unmaintained
Date:          2020-05-02
ID:            RUSTSEC-2020-0036
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0036
Dependency tree:
failure 0.1.8
└── ffsend-api 0.6.3
```

It can be somewhat easily remedied by replacing with another error crate like thiserror, anyhow, or eyre.

I would be willing to attempt to implement this and submit a PR if it would be accepted

**Comment by timvisee** [comment]
Thanks for your report. Yes, replacing this with `thiserror` and `anyhow` would be great.

> I would be willing to attempt to implement this and submit a PR if it would be accepted

Of course, that would be awesome! If you'd like to give this a try for the whole crate, go ahead.

I believe this will introduce breaking changes, as the error types are (obviously) exposed. This is fine, and we'll just release it as new minor version.

I'll probably take the work to update [`ffsend`](https://github.com/timvisee/ffsend) with these changes along side it.

**Comment by timvisee** [comment]
Would you like to give updating [`ffsend`](https://github.com/timvisee/ffsend) a try as well (with `ffsend-api` `v0.7.0`), or should I do this myself at a later time?
